export const users = [
  {
    id: 1,
    firstName: "Lizabeth",
    lastName: "Posvner",
    email: "lposvner0@squarespace.com",
    gender: "Genderfluid",
    ipAddress: "97.154.130.95",
  },
  {
    id: 2,
    firstName: "Dael",
    lastName: "Ramberg",
    email: "dramberg1@prnewswire.com",
    gender: "Genderqueer",
    ipAddress: "119.104.22.13",
  },
  {
    id: 3,
    firstName: "Leonora",
    lastName: "Lacroux",
    email: "llacroux2@timesonline.co.uk",
    gender: "Genderqueer",
    ipAddress: "162.72.55.244",
  },
  {
    id: 4,
    firstName: "Leanora",
    lastName: "Felder",
    email: "lfelder3@techcrunch.com",
    gender: "Female",
    ipAddress: "56.248.48.189",
  },
  {
    id: 5,
    firstName: "Abner",
    lastName: "Elmhurst",
    email: "aelmhurst4@hibu.com",
    gender: "Genderfluid",
    ipAddress: "81.234.149.181",
  },
  {
    id: 6,
    firstName: "Chiquita",
    lastName: "O'Hagerty",
    email: "cohagerty5@nhs.uk",
    gender: "Female",
    ipAddress: "125.197.136.21",
  },
  {
    id: 7,
    firstName: "Rachel",
    lastName: "Bungey",
    email: "rbungey6@biglobe.ne.jp",
    gender: "Genderqueer",
    ipAddress: "152.225.62.192",
  },
  {
    id: 8,
    firstName: "Esme",
    lastName: "Toma",
    email: "etoma7@mayoclinic.com",
    gender: "Bigender",
    ipAddress: "147.173.204.206",
  },
  {
    id: 9,
    firstName: "Ernie",
    lastName: "Lewis",
    email: "elewis8@oakley.com",
    gender: "Genderfluid",
    ipAddress: "147.37.125.12",
  },
  {
    id: 10,
    firstName: "Shannah",
    lastName: "Cowlas",
    email: "scowlas9@intel.com",
    gender: "Agender",
    ipAddress: "148.57.56.152",
  },
];
